- src/main/java/org/opensrp/web/rest/PlanResource.java
- src/test/java/org/opensrp/web/rest/PlanResourceTest.java
Revert functionality for getAll Plans API endpoint.
Currently its duplicating plans by the number of jurisdictions per plan
> Get all plans use plan service getall plans method

- pom.xml
Resolves #250 
Configure optional sync profiles variables with default profile
This is to allow specifying or omitting the default profiles 
- openmrs-sync
- dhis2-sync
> Configure optional sync profiles with default profile

- src/main/java/org/opensrp/web/rest/rapid/RapidProResource.java
Issue # 278
Refactor RapidProResource remove information leak.
There below variables are defines globally on the access which mean values are shared across all threads that make requests to the API
private List<Event> events;
private List<RapidProContact> rapidProContacts;
private RapidProContact rapidProContact;
private Client contactMother, contactChild;
private List<Obs> obs;
Move these variables to local variables on the functions that use them so that they are then request variables
> WIP  Refactor RapidProResource remove information leak

- src/main/java/org/opensrp/web/config/security/ResourceServerConfiguration.java
Issue # 254
To allow accessing UniqueIdController API's while using Bearer tokens for authentication.
> 254 : UniqueID API support Access via Access tokens

- src/main/java/org/opensrp/web/config/security/filter/XssPreventionRequestWrapper.java
This was causing errors as on below stacktrace
```
java.lang.IllegalStateException: getInputStream() has already been called for this request
at org.apache.catalina.connector.Request.getReader(Request.java:1208)
at org.apache.catalina.connector.RequestFacade.getReader(RequestFacade.java:504)
at javax.servlet.ServletRequestWrapper.getReader(ServletRequestWrapper.java:230)
at javax.servlet.ServletRequestWrapper.getReader(ServletRequestWrapper.java:230)
at javax.servlet.ServletRequestWrapper.getReader(ServletRequestWrapper.java:230)
at javax.servlet.ServletRequestWrapper.getReader(ServletRequestWrapper.java:230)
at org.opensrp.web.config.security.filter.XssPreventionRequestWrapper.getInputStream(XssPreventionRequestWrapper.java:44)
```
> Fix bug XSS wrapper use getInputSteam in overridden method

- pom.xml
- src/main/java/org/opensrp/web/config/security/SecurityConfig.java
- src/main/java/org/opensrp/web/controller/MultimediaController.java
- src/test/java/org/opensrp/web/controller/MultimediaControllerTest.java
> Multimedia exceptions catch in global exception handler

- .travis.yml
- pom.xml
- src/main/java/org/opensrp/web/config/security/HttpSessionConfig.java
> Fix session replication

- pom.xml
- src/main/java/org/opensrp/web/Constants.java
- src/main/java/org/opensrp/web/rest/ManifestResource.java
- src/test/java/org/opensrp/web/rest/ManifestResourceTest.java
- Enable the API to return the next available version(lower) of a manifest when strict param is not defined or when the strict param is false
- The API will return 404 when the strict param is true & manifest is not found
Fixes #331
> Add strict param in Manifest API Search endpoint

- pom.xml
- src/main/java/org/opensrp/web/Constants.java
- src/main/java/org/opensrp/web/controller/UserController.java
- src/main/java/org/opensrp/web/rest/ManifestResource.java
- src/test/java/org/opensrp/web/rest/ManifestResourceTest.java
- Enable the API to return the next available version(lower) of a manifest when strict param is not defined or when the strict param is false
- The API will return 404 when the strict param is true & manifest is not found
Fixes #331
> Add strict param in Manifest API Search endpoint v2.1

- pom.xml
- src/main/java/org/opensrp/web/rest/ClientFormResource.java
- src/test/java/org/opensrp/web/rest/ClientFormResourceTest.java
- If the content is not valid JSON, MVEL YAML Rule OR ML properties file, then a 400 is returned with a clear message on the error
- Fixes #328
> Validate client form uploads are valid JSON, YAML Rule definition & ML properties file

- pom.xml
- src/main/java/org/opensrp/web/rest/EventResource.java
Adding events is failing due to the following exception encountered when converting the event string to java objects using gson
`Sync data processing failed with exception org.json.JSONException: JSONObject["events"] not a string`
> Fix add event bug

- pom.xml
- src/main/java/org/opensrp/web/config/security/NotOAuthRequestMatcher.java
- src/main/java/org/opensrp/web/config/security/ResourceServerConfiguration.java
> Exclude oauth and unprotected endpoints from resource server

- pom.xml
- src/main/java/org/opensrp/web/rest/UserResource.java
- src/test/java/org/opensrp/web/rest/UserResourceTest.java
> Get keycloak users to string

- pom.xml
- src/test/java/org/opensrp/web/rest/SettingResourceTest.java
> Server version changes

- pom.xml
- src/main/java/org/opensrp/web/controller/UserController.java
- src/test/java/org/opensrp/web/rest/UserControllerTest.java
There are circumstances where the default locationId returned by the API belonged to  a team assignment whose plan is not currently active (e.g retired). 
This would lead to the android client not being able to populate the location drop-down resulting in an `Error Processing Location Hierarchy. Log off to download location hierarchy again` error.
> Default locationId search from intersection of plan locations and organization assigned locations

- src/main/java/org/opensrp/web/rest/ClientFormResource.java
- src/test/java/org/opensrp/web/rest/ClientFormResourceTest.java
Resolves #801 
Resolves OpenSRP/opensrp-client-anc#552
Get expected file version from manifest
For each file in a manifest release
- Check for version matching version from manifest `or` highest version below version from manifest 
- if not found, checks for the highest, most recent version
> Resolve `release file overriding previous releases`

- pom.xml
- src/main/java/org/opensrp/web/rest/v2/SettingResource.java
- src/test/java/org/opensrp/web/rest/v2/SettingResourceTest.java
Resolves https://github.com/opensrp/opensrp-server-web/issues/830
> 830 : Add limit and metadata version params in v2 settings get end-point

- pom.xml
- src/main/java/org/opensrp/web/rest/PlanResource.java
- src/test/java/org/opensrp/web/rest/PlanResourceTest.java
using 'revoke_assignments' parameter
closes #905
> make revoking team assignments for complete/retired plans optional

- README.md
- pom.xml
- src/main/java/org/opensrp/web/health/JdbcServiceHealthIndicator.java
- src/main/java/org/opensrp/web/health/KeycloakServiceHealthIndicator.java
- src/test/java/org/opensrp/TestDatabaseConfig.java
- src/test/java/org/opensrp/web/health/JdbcServiceHealthIndicatorTest.java
Add timeouts for postgres `2s`  and Keycloak `5s` indicators. This ensures that endpoint returns a response at ~5s at the most.
> Add timeout for health indicators v2.2

- README.md
- pom.xml
- src/main/java/org/opensrp/web/health/JdbcServiceHealthIndicator.java
- src/main/java/org/opensrp/web/health/OpenmrsServiceHealthIndicator.java
- src/test/java/org/opensrp/web/health/JdbcServiceHealthIndicatorTest.java
Add timeouts for postgres `2s`  and openmrs `5s` indicators. This ensures that endpoint returns a response at ~5s at the most.
> Add timeout for health indicators

- README.md
- pom.xml
- src/main/java/org/opensrp/web/Constants.java
- src/main/java/org/opensrp/web/config/HealthCheckMetricUpdater.java
- src/main/java/org/opensrp/web/config/MetricsConfiguration.java
- src/main/java/org/opensrp/web/config/SentryConfiguration.java
- src/main/java/org/opensrp/web/config/security/SecurityConfig.java
- src/main/java/org/opensrp/web/contract/ServiceHealthIndicator.java
- src/main/java/org/opensrp/web/controller/MetricsController.java
- src/main/java/org/opensrp/web/health/JdbcServiceHealthIndicator.java
- src/main/java/org/opensrp/web/health/KeycloakServiceHealthIndicator.java
- src/main/java/org/opensrp/web/health/RabbitmqServiceHealthIndicator.java
- src/main/java/org/opensrp/web/health/RedisServiceHealthIndicator.java
- src/main/java/org/opensrp/web/service/HealthService.java
- src/main/java/org/opensrp/web/serviceimpl/HealthServiceImpl.java
- src/main/webapp/index.html
- src/test/java/org/opensrp/TestDatabaseConfig.java
- src/test/java/org/opensrp/web/config/HealthCheckMetricUpdaterTest.java
- src/test/java/org/opensrp/web/config/MetricsConfigurationTest.java
- src/test/java/org/opensrp/web/controller/MetricsControllerTest.java
- src/test/resources/test-webmvc-config.xml
- Adds opensrp server metrics, i.e jvm_gc,jvm_thread,cpu, diskspace,log4j,jvm_memory
- Adds custom metrics for health check.
- Exposes the `/opensrp/metrics` unauthenticated on local ips i.e (`127.0.0.1` and value of `InetAddress.getLocalHost().getHostAddress()`)   and one additional configurable ip otherwise it will require authentication for the rest.
> add opensrp server metrics

- pom.xml
- src/main/java/org/opensrp/web/config/MetricsConfiguration.java
- src/main/java/org/opensrp/web/config/SentryConfiguration.java
- src/test/java/org/opensrp/web/config/SentryConfigurationTest.java
Fixes issue with string conversion on docker container.
> add quotes on map defaults (fixes issue in docker env)

- pom.xml
- src/main/java/org/opensrp/web/serviceimpl/HealthServiceImpl.java
- src/test/resources/test-webmvc-config.xml
This change provides a threadpooltaskexecutor bean that can be used as singleton instead of initializing Executor service when needed. This will prevent multiple executor service from being created.
> replace executorservice with taskexecutor bean

- pom.xml
- src/main/java/org/opensrp/web/serviceimpl/HealthServiceImpl.java
- src/test/resources/test-webmvc-config.xml
This change provides a threadpooltaskexecutor bean that can be used as singleton instead of initializing Executor service when needed. This will prevent multiple executor service from being created.
> Update use task executor bean v2.1

- pom.xml
- src/main/java/org/opensrp/web/serviceimpl/HealthServiceImpl.java
- src/test/resources/test-webmvc-config.xml
This change provides a threadpooltaskexecutor bean that can be used as singleton instead of initializing Executor service when needed. This will prevent multiple executor service from being created.
> replace executorservice with taskexecutor beanv3

- pom.xml
- Server core to 2.12.17
- Server connector to 2.3.2-SNAPSHOT
- Spring security to 5.3.12.RELEASE
- Log4j-slf4j-impl to 2.15.0
- Log4j-jcl to 2.15.0
Bump up artifact version to 2.1.54.2
> Security updates: Migrate dependencies v2.1

- pom.xml
- src/main/java/org/opensrp/web/rest/PlanResource.java
- src/test/java/org/opensrp/web/rest/PlanResourceTest.java
**Security updates: Migrate dependencies**
- Server core to 2.12.17
- Server connector to 2.3.2-SNAPSHOT
- Spring security to 5.3.12.RELEASE
- log4j-slf4j-impl to 2.15.0
- log4j-jcl to 2.15.0
Bump up artifact version to 2.3.8
> Security updates: Migrate dependencies v2.2

- README.md
- pom.xml
**Migrate dependencies**
- Server core to 3.0.8
- Server connector to 2.3.2-SNAPSHOT
- Spring security to 5.3.12.RELEASE
> Security patches

- pom.xml
- src/main/java/org/opensrp/web/Constants.java
- src/main/java/org/opensrp/web/rest/PlanResource.java
- src/test/java/org/opensrp/web/rest/PlanResourceTest.java
There is a need to add logging of errors in the plan generation process. These will be logged in the `error_log` field in the plan_processing_status table
> Add plan generation error logging

- pom.xml
- src/main/java/org/opensrp/web/GlobalExceptionHandler.java
- src/main/java/org/opensrp/web/rest/EventResource.java
- src/test/java/org/opensrp/web/rest/EventResourceTest.java
> Allow Move to My Catchment Events Sync Without Location Filter

- README.md
- pom.xml
- src/main/java/org/opensrp/web/config/security/SecurityConfig.java
- Update sentry log4j to 5.5.0
- Update log4j to v2.16.0
- Remove whitelisting of the value of InetAddress.getLocalHost().getHostAddress() since in some servers it returns public ip.
- Update readme to reflect the above change.
> Log4j security patch

- README.md
- pom.xml
- src/main/java/org/opensrp/web/config/security/SecurityConfig.java
- Update sentry log4j to 5.5.0
- Update log4j to v2.16.0
- Remove whitelisting of the value of InetAddress.getLocalHost().getHostAddress() since in some servers it returns public ip.
- Update readme to reflect the above change.
> Log4j security patch v2.2

- README.md
- pom.xml
- src/main/java/org/opensrp/web/config/security/ResourceServerConfiguration.java
- src/test/java/org/opensrp/web/health/RabbitmqServiceHealthIndicatorTest.java
- Update sentry log4j to 5.5.0
- Update log4j to v2.16.0
- Remove whitelisting of the value of InetAddress.getLocalHost().getHostAddress() since in some servers it returns public ip.
- Update readme to reflect the above change.
> Log4j security patch v2.1

- pom.xml
Posting templates via the `rest/templates` API is failing due to an error during de-serialization of the template
> Fix plan template action deserialization

- pom.xml
Fixes [CVE-2021-45105](https://nvd.nist.gov/vuln/detail/CVE-2021-45105) vulnerability.
> update log4j dependencies

- pom.xml
Retrieving case details events during plan generation on production is failing due to not using the event id in the repository method
> Fix get case detail event issue

- Dockerfile
- pom.xml
- closes #1088 
- use tomcat correto jdk images.
> Add mybatis runtime feature

- .dockerignore
- .github/workflows/ci.yml
- .github/workflows/docker-docs.yml
- .github/workflows/docker-publish.yml
- docs/how-to-use-docker-image.md
- Adds `docs` directory which will hold documentations on how to setup and use opensrp server web.
- Adds a github action workflow which updates dockerhub readme.
- `docs/how-to-use-docker-image.md` has the contents of dockerhub readme.
> add docker docs updater

- pom.xml
- src/main/java/org/opensrp/web/rest/EventResource.java
Include request JSON for each failed clients and events in the log entry for troubleshooting
> Log More Details for Clients/Events That Fail to Sync

- pom.xml
- Made `throw_warning` false to prevent warning msgs from halting the migration process.
> allow migrations to continue after getting warning msgs

- pom.xml
- Made `throw_warning` false to prevent warning msgs from halting the migration process.
> Allow migration continue after warning msgs v2.1
