opensrp/opensrp-server-web

- pom.xml
- src/main/java/org/opensrp/web/rest/CampaignResource.java
- src/main/java/org/opensrp/web/rest/TaskResource.java
- src/main/resources/quartz.properties
- src/test/java/org/opensrp/web/rest/CampaignResourceTest.java
- src/test/java/org/opensrp/web/rest/TaskResourceTest.java
- src/test/java/org/opensrp/web/rest/shadow/CampaignResourceShadow.java
- src/test/java/org/opensrp/web/rest/shadow/TestResourceShadow.java
- src/test/resources/test-webmvc-config.xml
Implement Campaign and Task endpoints
**Resolves**
- OpenSRP/opensrp-server-web#4
- OpenSRP/opensrp-server-web#5
Depends on [https://github.com/OpenSRP/opensrp-server-core/pull/7](https://github.com/OpenSRP/opensrp-server-core/pull/7)
> Create campaign task api

- pom.xml
- src/main/java/org/opensrp/web/rest/LocationResource.java
- src/main/java/org/opensrp/web/rest/TaskResource.java
- src/test/java/org/opensrp/web/rest/CampaignResourceTest.java
- src/test/java/org/opensrp/web/rest/LocationResourceTest.java
- src/test/java/org/opensrp/web/rest/TaskResourceTest.java
- src/test/java/org/opensrp/web/rest/shadow/LocationResourseShadow.java
- src/test/java/org/opensrp/web/rest/shadow/TaskResourceShadow.java
- src/test/resources/test-webmvc-config.xml
PR for Issue [https://github.com/OpenSRP/opensrp-server-web/issues/3](https://github.com/OpenSRP/opensrp-server-web/issues/3)
Depends on PRs
-  [https://github.com/OpenSRP/opensrp-server-configs/pull/2](https://github.com/OpenSRP/opensrp-server-configs/pull/2)
- [https://github.com/OpenSRP/opensrp-server-core/pull/8](https://github.com/OpenSRP/opensrp-server-core/pull/8)
> Create location API

- pom.xml
- src/main/java/org/opensrp/web/rest/CampaignResource.java
- src/main/java/org/opensrp/web/rest/LocationResource.java
- src/main/java/org/opensrp/web/rest/TaskResource.java
- src/test/java/org/opensrp/web/rest/CampaignResourceTest.java
- src/test/java/org/opensrp/web/rest/LocationResourceTest.java
- src/test/java/org/opensrp/web/rest/TaskResourceTest.java
PR for Issue [https://github.com/OpenSRP/opensrp-server-web/issues/24](https://github.com/OpenSRP/opensrp-server-web/issues/24)
Depends on [https://github.com/OpenSRP/opensrp-server-core/pull/10](https://github.com/OpenSRP/opensrp-server-core/pull/10)
> Differentiate response HTTP status codes and allow text/plain mime type

- pom.xml
- src/main/java/org/opensrp/web/rest/LocationResource.java
- src/test/java/org/opensrp/web/rest/LocationResourceTest.java
Fixes [https://github.com/OpenSRP/opensrp-server-web/issues/42](https://github.com/OpenSRP/opensrp-server-web/issues/42)
Depends On [https://github.com/OpenSRP/opensrp-server-core/pull/27](https://github.com/OpenSRP/opensrp-server-core/pull/27)
> Search structures family details from coordinates API endpoints

- pom.xml
- src/main/java/org/opensrp/web/controller/UserController.java
- src/main/resources/spring/oauth-authorization.xml
- src/test/java/org/opensrp/web/rest/UserControllerTest.java
- src/test/java/org/opensrp/web/rest/shadow/UserControllerShadow.java
- src/test/resources/test-webmvc-config.xml
Fixes [https://github.com/OpenSRP/opensrp-server-web/issues/44](https://github.com/OpenSRP/opensrp-server-web/issues/44)
Depends on
-  [https://github.com/OpenSRP/opensrp-server-configs/pull/12](https://github.com/OpenSRP/opensrp-server-configs/pull/12)
- [https://github.com/OpenSRP/opensrp-server-common/pull/5](https://github.com/OpenSRP/opensrp-server-common/pull/5)
> User details API default to logged in user ,  restrict callback URL

- pom.xml
- src/main/java/org/opensrp/web/CorsFilter.java
- src/main/java/org/opensrp/web/GzipResponseStream.java
- src/main/java/org/opensrp/web/HttpHeaderFactory.java
- src/main/java/org/opensrp/web/controller/UserController.java
- src/main/resources/spring/oauth-authorization.xml
- src/main/webapp/WEB-INF/web.xml
Fixes [https://github.com/OpenSRP/opensrp-server-web/issues/48](https://github.com/OpenSRP/opensrp-server-web/issues/48)
> Enable CORS

- .travis.yml
- pom.xml
- src/main/java/org/opensrp/web/rest/PlanResource.java
- src/test/java/org/opensrp/web/rest/BaseResourceTest.java
- src/test/java/org/opensrp/web/rest/PlanResourceTest.java
- src/test/java/org/opensrp/web/rest/shadow/PlanResourceShadow.java
- src/test/resources/test-persistence-postgres.xml
- src/test/resources/test-webmvc-config.xml
Depends on https://github.com/OpenSRP/opensrp-server-core/pull/28.
Closes #41
> Implement planning resource end points

- src/main/resources/spring/oauth-authorization.xml
- src/main/resources/spring/oauth_clients.xml
> Move declaration of Oauth clients to separate file

- pom.xml
- src/main/java/org/opensrp/web/rest/EventResource.java
- src/main/java/org/opensrp/web/security/DrishtiAuthenticationProvider.java
- src/main/resources/spring/basic_auth.xml
- src/main/resources/spring/oauth-authorization.xml
- src/test/java/org/opensrp/web/security/OauthAuthenticationProviderTest.java
Fixes #56 
Depends on [https://github.com/OpenSRP/opensrp-server-core/pull/32](https://github.com/OpenSRP/opensrp-server-core/pull/32)
> Add Events getAll endpoint

- src/main/java/org/opensrp/web/rest/EventResource.java
- src/main/java/org/opensrp/web/rest/LocationResource.java
- src/main/java/org/opensrp/web/rest/PlanResource.java
- src/main/java/org/opensrp/web/rest/RestUtils.java
- src/main/java/org/opensrp/web/rest/StockResource.java
- src/main/java/org/opensrp/web/rest/TaskResource.java
- src/main/java/org/opensrp/web/rest/ValidateResource.java
> Add JSON  content type and UTF-8 charset headers

- pom.xml
- src/test/java/org/opensrp/web/rest/TaskResourceTest.java
Add reasonReference to Task.
Depends on https://github.com/OpenSRP/opensrp-server-core/issues/33
> Upgrade opensrp server core version

- src/main/resources/spring/securityContext.xml
- src/main/webapp/WEB-INF/spring/webmvc-config.xml
> Static resources mapping security

- .travis.yml
- pom.xml
- src/main/java/org/opensrp/web/rest/LocationResource.java
- src/main/webapp/WEB-INF/spring/webmvc-config.xml
> Add location properties converter to support additional properties

- src/main/java/org/opensrp/web/CorsFilter.java
- src/main/resources/spring/basic_auth.xml
- src/main/resources/spring/oauth-authorization.xml
> Whitelist OPTIONS HTTP method. CORS allow POST and PUT  

- pom.xml
- src/main/java/org/opensrp/web/rest/LocationResource.java
- src/test/java/org/opensrp/web/rest/LocationResourceTest.java
Resolves #71 and Resolves #75
Depends on [https://github.com/OpenSRP/opensrp-server-core/pull/49](https://github.com/OpenSRP/opensrp-server-core/pull/49)
> Location API that filter's by properties and return Geometry optionally

- src/main/java/org/opensrp/web/controller/UserController.java
- src/main/java/org/opensrp/web/rest/PlanResource.java
Resolves #86  Closes [https://github.com/OpenSRP/opensrp-client-reveal/issues/271](https://github.com/OpenSRP/opensrp-client-reveal/issues/271)
> User Controller use utf8 encoding

- pom.xml
- src/main/java/org/opensrp/web/security/DrishtiAuthenticationProvider.java
- src/main/java/org/opensrp/web/security/OauthAuthenticationProvider.java
- src/test/java/org/opensrp/web/security/OauthAuthenticationProviderTest.java
> Basic auth requests cache auth on redis for oauth2 enabled server

- pom.xml
Depends [https://github.com/OpenSRP/opensrp-server-core/pull/51/](https://github.com/OpenSRP/opensrp-server-core/pull/51/)
> Upgrade core library to resolve plans endpoint performance issues

- pom.xml
- src/main/java/org/opensrp/web/rest/LocationResource.java
- src/test/java/org/opensrp/web/rest/LocationResourceTest.java
Resolves #89 Depends on https://github.com/OpenSRP/opensrp-server-core/pull/58
> Allow getting jurisdiction without geojson

- pom.xml
- src/main/java/org/opensrp/web/rest/LocationResource.java
> Make it possible to get more than one jurisdiction by id

- pom.xml
- src/main/java/org/opensrp/web/rest/PlanResource.java
- src/test/java/org/opensrp/web/rest/PlanResourceTest.java
Resolves #85 Depends on https://github.com/OpenSRP/opensrp-server-core/issues/62
> Request only certain fields from the plans endpoint

- pom.xml
- src/main/java/org/opensrp/web/rest/LocationResource.java
- src/test/java/org/opensrp/web/rest/LocationResourceTest.java
Resolves #90  Depends on https://github.com/OpenSRP/opensrp-server-core/issues/66
> Get all children and grand children of a jurisdiction

- pom.xml
- src/test/java/org/opensrp/web/rest/UserControllerTest.java
Upgrade server common to 
Correct User Details getter methods to work with Jackson new converters
> Upgrade server common

- pom.xml
> Use plan table only when querying for plans with optional fields

- pom.xml
- src/main/java/org/opensrp/web/config/SwaggerConfig.java
- src/main/resources/spring/basic_auth.xml
- src/main/resources/spring/oauth-authorization.xml
- src/main/resources/spring/oauth-common.xml
- src/main/resources/spring/securityContext.xml
Resolves #114 
Opened an Issue #116  to enable it.
> Disable Swagger Documentation

- pom.xml
- src/main/java/org/opensrp/web/bean/OrganizationAssigmentBean.java
- src/main/java/org/opensrp/web/rest/OrganizationResource.java
> Implement organization API including assignment

- pom.xml
- src/main/java/org/opensrp/web/rest/PractitionerResource.java
- src/main/java/org/opensrp/web/rest/PractitionerRoleResource.java
> Implement Practitioner and Practitioner Role API endpoints

- pom.xml
- src/main/java/org/opensrp/web/rest/LocationResource.java
- src/main/java/org/opensrp/web/rest/PlanResource.java
- src/main/java/org/opensrp/web/rest/TaskResource.java
- src/test/java/org/opensrp/web/rest/BaseResourceTest.java
- src/test/java/org/opensrp/web/rest/LocationResourceTest.java
- src/test/java/org/opensrp/web/rest/PlanResourceTest.java
- src/test/java/org/opensrp/web/rest/TaskResourceTest.java
> changed task sync API to post

- pom.xml
- src/main/java/org/opensrp/web/controller/UserController.java
- src/main/java/org/opensrp/web/rest/SettingResource.java
- src/test/java/org/opensrp/web/rest/SettingResourceTest.java
> Update setting resource to handle array of values

- pom.xml
- src/main/java/org/opensrp/web/rest/SearchResource.java
- src/main/java/org/opensrp/web/utils/ChildMother.java
- src/main/java/org/opensrp/web/utils/SearchEntityWrapper.java
- src/main/java/org/opensrp/web/utils/SearchHelper.java
- src/test/java/org/opensrp/web/rest/SearchResourceTest.java
- src/test/java/org/opensrp/web/utils/RestUtilsTest.java
- src/test/java/org/opensrp/web/utils/SearchHelperTest.java
- Refactor _search/path_ implementation for maintainability
- [Fixes Issue 144](https://github.com/OpenSRP/opensrp-server-web/issues/144)
> Fix search/path endpoint search not working for various fields

- pom.xml
> Validate user id is unique when creating new practitioner

- pom.xml
- src/main/java/org/opensrp/web/rest/OrganizationResource.java
- src/test/java/org/opensrp/web/rest/shadow/OrganizationResourceShadow.java
> Endpoint to get practitioners assigned to an organization

- src/main/java/org/opensrp/web/bean/SyncParam.java
- src/main/java/org/opensrp/web/rest/EventResource.java
>  Event sync support post

- pom.xml
- src/main/java/org/opensrp/web/utils/SearchHelper.java
Migrate to connector library v1.0.4-SNAPSHOT version
> Fix search endpoint not working for mother/guardian last name

- pom.xml
- src/main/java/org/opensrp/web/rest/EventResource.java
- src/main/java/org/opensrp/web/rest/LocationResource.java
- src/main/java/org/opensrp/web/rest/PractitionerRoleResource.java
- src/main/java/org/opensrp/web/rest/TaskResource.java
> Add an way to get all object ids for events, structures and tasks

- pom.xml
- src/main/java/org/opensrp/web/rest/UserResource.java
- src/test/java/org/opensrp/web/rest/UserResourceTest.java
- src/test/java/org/opensrp/web/rest/shadow/UserResourceShadow.java
- src/test/resources/test-webmvc-config.xml
Resolves #133
Depends on https://github.com/OpenSRP/opensrp-server-connector/pull/11
> Add API to Get openmsr users

- pom.xml
- src/main/java/org/opensrp/web/CorsFilter.java
- src/main/java/org/opensrp/web/rest/PractitionerResource.java
- src/main/java/org/opensrp/web/rest/PractitionerRoleResource.java
- src/test/java/org/opensrp/web/rest/BaseResourceTest.java
- src/test/java/org/opensrp/web/rest/PractitionerResourceTest.java
- src/test/java/org/opensrp/web/rest/PractitionerRoleResourceTest.java
> Support deletion of practitioner roles

- pom.xml
- src/main/java/org/opensrp/web/rest/LocationResource.java
- src/main/java/org/opensrp/web/rest/OrganizationResource.java
> Add UTF-8 headers

- pom.xml
- src/main/java/org/opensrp/web/controller/MultimediaController.java
- src/main/java/org/opensrp/web/rest/RestUtils.java
- src/main/resources/spring/basic_auth.xml
- src/test/java/org/opensrp/web/utils/RestUtilsTest.java
- src/test/java/org/opensrp/web/utils/test_file_1
- src/test/java/org/opensrp/web/utils/test_file_2
- src/test/java/org/opensrp/web/utils/test_file_3
> Add sync by content type and file category

- pom.xml
- src/main/java/org/opensrp/web/rest/EventResource.java
> Add endpoint to search events by id

- pom.xml
- src/main/java/org/opensrp/web/controller/UserController.java
> Fix bugs on building OpenMRS location tree

- pom.xml
- src/main/java/org/opensrp/web/rest/LocationResource.java
- src/main/java/org/opensrp/web/rest/PlanResource.java
- src/test/java/org/opensrp/web/rest/LocationResourceTest.java
- src/test/java/org/opensrp/web/rest/PlanResourceTest.java
- src/test/java/org/opensrp/web/rest/shadow/PlanResourceShadow.java
> Implement endpoint to get location names by plan id

- pom.xml
- src/main/java/org/opensrp/web/Constants.java
- src/main/java/org/opensrp/web/rest/LocationResource.java
- src/main/java/org/opensrp/web/rest/PlanResource.java
- src/main/java/org/opensrp/web/rest/TaskResource.java
- src/main/java/org/opensrp/web/utils/Constants.java
- src/main/resources/spring/basic_auth.xml
- src/test/java/org/opensrp/web/rest/LocationResourceTest.java
- src/test/java/org/opensrp/web/rest/PlanResourceTest.java
- src/test/java/org/opensrp/web/rest/TaskResourceTest.java
> Basic paginated/incremental serverVersion endpoints for all OpenSRP entities

- pom.xml
- src/main/java/org/opensrp/web/controller/XlsDataImportController.java
- src/main/java/org/opensrp/web/rest/SearchResource.java
- src/main/java/org/opensrp/web/utils/SearchHelper.java
- src/test/java/org/opensrp/web/controller/XlsDataImportControllerTest.java
- src/test/java/org/opensrp/web/utils/SearchHelperTest.java
Added identifier search filters for opensrp_id, simprints_guid
Fixed Tests
Co-authored-by: Martin Ndegwa <ndegwamartin@gmail.com>
> Made changes to separate mother zeir_id from child zeir_id

- pom.xml
- src/main/java/org/opensrp/web/rest/EventResource.java
- src/test/java/org/opensrp/web/rest/BaseResourceTest.java
- src/test/java/org/opensrp/web/rest/EventResourceTest.java
- src/test/java/org/opensrp/web/rest/shadow/EventResourceShadow.java
- src/test/resources/test-webmvc-config.xml
> Optionally return ids for archived events

- pom.xml
> Upgrade core library to 1.3.6

- pom.xml
> Upgrade core library

- pom.xml
- src/main/webapp/WEB-INF/web.xml
> OpenMRS and DHIS2 sync Configuration

- pom.xml
- src/main/java/org/opensrp/web/controller/LocationController.java
- src/test/java/org/opensrp/web/controller/LocationControllerTest.java
[issue 205](https://github.com/OpenSRP/opensrp-server-web/issues/205)
> Implement endpoint for getting location by level and tags

- pom.xml
- src/main/java/org/opensrp/web/Constants.java
- src/main/java/org/opensrp/web/bean/Identifier.java
- src/main/java/org/opensrp/web/rest/EventResource.java
- src/main/java/org/opensrp/web/rest/LocationResource.java
- src/main/java/org/opensrp/web/rest/PlanResource.java
- src/main/java/org/opensrp/web/rest/TaskResource.java
- src/test/java/org/opensrp/web/controller/LocationControllerTest.java
- src/test/java/org/opensrp/web/rest/EventResourceTest.java
- src/test/java/org/opensrp/web/rest/LocationResourceTest.java
- src/test/java/org/opensrp/web/rest/PlanResourceTest.java
- src/test/java/org/opensrp/web/rest/TaskResourceTest.java
> Add endpoints to get all ids for plans and jurisdictions

- pom.xml
> Upgrade opensrp server commmon

- pom.xml
- src/main/java/org/opensrp/web/rest/ClientResource.java
Feature:
1. ANC list
2. Child list.
3. Implement comma separated location ids.
#219
> ANC and child list API

- pom.xml
Depends on https://github.com/OpenSRP/opensrp-server-core/pull/166
> Bump opensrp server core version

- pom.xml
Resolves #252 
Depends on https://github.com/OpenSRP/opensrp-server-core/pull/173
> Remove schedules configuration

- pom.xml
- src/main/java/org/opensrp/web/controller/MultimediaController.java
- src/test/java/org/opensrp/web/controller/MultimediaControllerTest.java
Refactor multimedia dependencies
> Refactor multimedia dependencies

- pom.xml
- src/main/java/org/opensrp/web/Constants.java
- src/main/java/org/opensrp/web/bean/Identifier.java
- src/main/java/org/opensrp/web/controller/AuditMessageController.java
- src/main/java/org/opensrp/web/controller/LocationController.java
- src/main/java/org/opensrp/web/rest/ClientResource.java
- src/main/java/org/opensrp/web/rest/EventResource.java
- src/main/java/org/opensrp/web/rest/LocationResource.java
- src/main/java/org/opensrp/web/rest/PlanResource.java
- src/main/java/org/opensrp/web/rest/TaskResource.java
- src/main/resources/spring/applicationContext-opensrp-web.xml
- src/test/java/org/opensrp/web/controller/LocationControllerTest.java
- src/test/java/org/opensrp/web/controller/MultimediaControllerTest.java
- src/test/java/org/opensrp/web/controller/it/AuditMessageControllerIntegrationTest.java
- src/test/java/org/opensrp/web/rest/EventResourceTest.java
- src/test/java/org/opensrp/web/rest/LocationResourceTest.java
- src/test/java/org/opensrp/web/rest/PlanResourceTest.java
- src/test/java/org/opensrp/web/rest/TaskResourceTest.java
> Merge master branch including dependent libraries, Upgrade Jackson

- pom.xml
- src/main/java/org/opensrp/web/controller/ActionController.java
- src/main/java/org/opensrp/web/controller/AuditMessageController.java
- src/main/java/org/opensrp/web/security/DrishtiAuthenticationProvider.java
- src/test/java/org/opensrp/web/rest/it/StockResourceTest.java
Issue # 231
Remove dependency of ch.lambdaj library and use JDK lambas
> WIP | Deprecate ch.lambdaj library and use JDK lamdas

- pom.xml
- src/main/java/org/opensrp/web/rest/LocationTagResource.java
- src/test/java/org/opensrp/web/rest/LocationTagResourceTest.java
- src/test/java/org/opensrp/web/rest/shadow/LocationTagResourceShadow.java
- src/test/resources/test-webmvc-config.xml
> location tag API endpoint

- src/main/webapp/WEB-INF/jsp/access_confirmation.jsp
Issue # 279
Remove Information leak.
On the file access_confirmation.jsp .Remove the call that notifies the user the reason why access could not be granted. Use Generic message
Access could not be granted. (<%=((AuthenticationException) session						.getAttribute(AbstractAuthenticationProcessingFilter.SPRING_SECURITY_LAST_EXCEPTION_KEY)).getMessage()%>)
> WIP | Remove Information Leak

- pom.xml
- src/main/java/org/opensrp/web/config/SwaggerConfig.java
- src/test/java/org/opensrp/web/config/SwaggerConfigTest.java
Issue # 116
Enable Swagger Documentation.
> WIP | Enable Swagger Documentation

- pom.xml
- src/main/java/org/opensrp/web/config/security/BasicAuthSecurityConfig.java
> Disable CSRF for basic auth profile

- src/test/java/org/opensrp/web/rest/ClientResourceTest.java
- src/test/java/org/opensrp/web/rest/EventResourceTest.java
- src/test/java/org/opensrp/web/rest/PlanResourceTest.java
- src/test/java/org/opensrp/web/rest/ReportResourceTest.java
- src/test/java/org/opensrp/web/rest/StockResourceTest.java
- src/test/java/org/opensrp/web/rest/ValidateResourceTest.java
> WIP : Add Missing Unit tests on API and Document changes

- src/main/java/org/opensrp/web/config/Role.java
- src/main/java/org/opensrp/web/config/security/BasicAuthSecurityConfig.java
- src/main/java/org/opensrp/web/config/security/ResourceServerConfiguration.java
- src/main/java/org/opensrp/web/rest/PlanResource.java
- src/main/java/org/opensrp/web/security/DrishtiAuthenticationProvider.java
- src/test/java/org/opensrp/web/rest/PlanResourceTest.java
- src/test/java/org/opensrp/web/security/OauthAuthenticationProviderTest.java
> Fetch user plans endpoint

- pom.xml
- src/main/java/org/opensrp/web/config/security/filter/CrossSiteScriptingPreventionFilter.java
- src/test/java/org/opensrp/web/controller/MultimediaControllerTest.java
- src/test/java/org/opensrp/web/controller/UniqueIdControllerTest.java
- src/test/java/org/opensrp/web/controller/UserControllerTest.java
- src/test/java/org/opensrp/web/controller/XlsDataImportControllerTest.java
> CrossSiteScriptingPreventionFilter suppport Encoding for Non JSON API

- pom.xml
- src/main/java/org/opensrp/web/Constants.java
- src/main/java/org/opensrp/web/rest/ClientFormResource.java
- src/test/java/org/opensrp/TestFileContent.java
- src/test/java/org/opensrp/web/rest/ClientFormResourceTest.java
> Enable uploading of relevance yaml files, calculation yaml files & property files

- pom.xml
- src/main/java/org/opensrp/web/rest/ClientResource.java
- src/test/java/org/opensrp/web/rest/ClientResourceTest.java
> Fetch all client ids

- pom.xml
- src/main/java/org/opensrp/web/bean/ResetPasswordBean.java
- src/main/java/org/opensrp/web/rest/UserResource.java
- src/test/java/org/opensrp/TestSecurityConfig.java
- src/test/java/org/opensrp/web/rest/UserControllerTest.java
- src/test/java/org/opensrp/web/rest/UserResourceTest.java
- src/test/resources/test-webmvc-config.xml
> Allow password change

- pom.xml
- src/main/java/org/opensrp/web/controller/UserController.java
- src/test/java/org/opensrp/web/controller/LocationControllerTest.java
- src/test/java/org/opensrp/web/rest/PlanResourceTest.java
- src/test/java/org/opensrp/web/rest/UserControllerTest.java
- src/test/java/org/opensrp/web/rest/shadow/UserControllerShadow.java
Resolves #307 
Depends on https://github.com/OpenSRP/opensrp-server-core/pull/200
> Decouple locations from openmrs

- pom.xml
- src/main/resources/spring/applicationContext-opensrp-web.xml
> Update multimedia keys

- src/test/java/org/opensrp/web/rest/EventResourceTest.java
> Fix failing add event test

- src/main/java/org/opensrp/web/rest/ValidateResource.java
- src/test/java/org/opensrp/web/rest/ValidateResourceTest.java
> Fix deserialization of events and clients json arrays

- pom.xml
- src/main/java/org/opensrp/web/controller/LocationController.java
- src/test/java/org/opensrp/web/controller/LocationControllerTest.java
- src/test/java/org/opensrp/web/rest/EventResourceTest.java
- src/test/resources/test-webmvc-config.xml
Signed-off-by: Elly Kitoto <junkmailstoelly@gmail.com>
> Implement fetch openmrs locations by team ids

- pom.xml
- src/main/java/org/opensrp/web/rest/EventResource.java
- src/main/java/org/opensrp/web/rest/ValidateResource.java
- src/main/java/org/opensrp/web/utils/Utils.java
- src/test/java/org/opensrp/web/rest/ValidateResourceTest.java
> Handle syncing of strings

- pom.xml
Migrate to latest core version (2.4.3 Snapshot)
> Migrate to latest core version (2.4.3 Snapshot)

- pom.xml
- src/main/java/org/opensrp/web/rest/ClientFormResource.java
- src/test/java/org/opensrp/web/rest/ClientFormResourceTest.java
> Add API to fetch draft & non-draft forms

- pom.xml
> Updated server core version

- pom.xml
- src/main/java/org/opensrp/web/rest/ClientFormResource.java
- src/main/java/org/opensrp/web/rest/ManifestResource.java
- src/main/java/org/opensrp/web/utils/FormConfigUtils.java
- src/test/java/org/opensrp/web/rest/BaseResourceTest.java
- src/test/java/org/opensrp/web/rest/ManifestResourceTest.java
- src/test/java/org/opensrp/web/rest/shadow/ManifestResourceShadow.java
Allow posting the Manifest JSON only & generate a new Manifest + associated properties then save
----
- See https://github.com/OpenSRP/opensrp-server-web/issues/382 for details
> Auto generate new Manifest & associated properties

- src/main/java/org/opensrp/web/rest/ClientFormResource.java
- src/test/java/org/opensrp/web/rest/ClientFormResourceTest.java
- Forms should use the form names as the form identifiers
----
See https://github.com/OpenSRP/opensrp-server-web/issues/344 for details
> Use form name as identifiers

- pom.xml
- src/main/java/org/opensrp/web/rest/ClientFormResource.java
- src/test/java/org/opensrp/web/rest/ClientFormResourceTest.java
Add file relationships when uploading the files
- This will allow retrieving, for instance, a JSON form and all associated files/forms
----
See https://github.com/OpenSRP/opensrp-server-web/issues/366 for details
> Add file relationships for associated JSON form

- pom.xml
- src/main/java/org/opensrp/web/rest/PlanResource.java
- src/main/java/org/opensrp/web/rest/TaskResource.java
- src/test/java/org/opensrp/web/rest/PlanResourceTest.java
- src/test/java/org/opensrp/web/rest/TaskResourceTest.java
> Extend Plan API to return templates

- pom.xml
- src/main/java/org/opensrp/web/rest/UploadController.java
Allow multiple column upload config
> Allow multiple column upload config

- pom.xml
- src/main/java/org/opensrp/web/rest/ManifestResource.java
- src/test/java/org/opensrp/web/rest/ManifestResourceTest.java
- Fix for potential bug 
- See https://github.com/OpenSRP/opensrp-server-web/issues/423 for details
> Merge identifiers in manifest auto-generation

- src/main/java/org/opensrp/web/rest/v2/SettingResource.java
- src/main/java/org/opensrp/web/utils/FormConfigUtils.java
- src/test/java/org/opensrp/web/rest/ClientFormResourceTest.java
- src/test/java/org/opensrp/web/utils/FormConfigUtilsTest.java
- src/test/java/org/opensrp/web/utils/OpenmrsHttpUtil.java
> Bug fixes for the form version generation

- pom.xml
- src/main/java/org/opensrp/web/rest/LocationResource.java
- src/test/java/org/opensrp/web/rest/LocationResourceTest.java
> Optimize location hierarchy api

- pom.xml
- src/main/java/org/opensrp/web/Constants.java
- src/main/java/org/opensrp/web/bean/EventSyncBean.java
- src/main/java/org/opensrp/web/bean/SyncParam.java
- src/main/java/org/opensrp/web/controller/UserController.java
- src/main/java/org/opensrp/web/rest/EventResource.java
- src/main/java/org/opensrp/web/rest/LocationResource.java
- src/main/java/org/opensrp/web/rest/PlanResource.java
- src/main/java/org/opensrp/web/rest/TaskResource.java
- src/test/java/org/opensrp/web/rest/EventResourceTest.java
- src/test/java/org/opensrp/web/rest/LocationResourceTest.java
- src/test/java/org/opensrp/web/rest/PlanResourceTest.java
- src/test/java/org/opensrp/web/rest/TaskResourceTest.java
- src/test/java/org/opensrp/web/rest/UserControllerTest.java
Resolves #346 on master branch
> Return Number of records Available for sync 

- pom.xml
- src/main/java/org/opensrp/web/controller/UserController.java
- src/main/java/org/opensrp/web/rest/LocationResource.java
- src/test/java/org/opensrp/web/rest/LocationResourceTest.java
- src/test/java/org/opensrp/web/rest/UserControllerTest.java
- src/test/java/org/opensrp/web/rest/shadow/LocationResourseShadow.java
Resolves #420 on master branch
> Jurisdiction tree for plan master

- pom.xml
- src/main/java/org/opensrp/web/rest/RestResource.java
> Base rest resource provide base type

- pom.xml
- Migrates to new server connector lib version
- Narrows logging output of openmrs location fetch requests
> Migrate to new connector library

- src/main/java/org/opensrp/web/rest/UserResource.java
- src/test/java/org/opensrp/web/rest/UserResourceTest.java
> Return all keycloak Users 

- pom.xml
- src/main/java/org/opensrp/web/rest/ClientResource.java
- src/test/java/org/opensrp/web/rest/ClientResourceTest.java
> Client get all endpoint

- pom.xml
- src/main/java/org/opensrp/web/config/security/WebConfig.java
> Enable async and upgrade libs

- src/main/java/org/opensrp/web/controller/UserController.java
- src/main/java/org/opensrp/web/rest/UserResource.java
- src/test/java/org/opensrp/web/rest/UserControllerTest.java
- src/test/java/org/opensrp/web/rest/UserResourceTest.java
> 468 logout cascade to keycloak

- src/main/java/org/opensrp/web/controller/UserController.java
- src/test/java/org/opensrp/web/rest/UserControllerTest.java
Related to https://github.com/onaio/reveal-frontend/issues/1224
> Clear cookies and invalidate session during logout

- src/main/java/org/opensrp/web/GlobalExceptionHandler.java
- src/main/java/org/opensrp/web/bean/UserAssignmentBean.java
- src/main/java/org/opensrp/web/rest/OrganizationResource.java
- src/test/java/org/opensrp/web/controller/XlsDataImportControllerTest.java
- src/test/java/org/opensrp/web/rest/BaseSecureResourceTest.java
- src/test/java/org/opensrp/web/rest/OrganizationResourceTest.java
- src/test/java/org/opensrp/web/rest/UploadControllerTest.java
- src/test/java/org/opensrp/web/rest/UserControllerTest.java
- src/test/java/org/opensrp/web/utils/TestData.java
- src/test/resources/test-webmvc-config.xml
> Add an API for returning assignments for a user

- pom.xml
> Allow disabling of plan generation

- .gitignore
- pom.xml
- src/main/java/org/opensrp/web/controller/UserController.java
- src/main/java/org/opensrp/web/rest/LocationResource.java
Resolves #527 
Depends on https://github.com/OpenSRP/opensrp-server-core/pull/316
> Support sync jurisdictions by

- pom.xml
- src/main/java/org/opensrp/web/GlobalExceptionHandler.java
- src/main/java/org/opensrp/web/controller/UserController.java
- src/main/java/org/opensrp/web/rest/OrganizationResource.java
- src/test/java/org/opensrp/web/rest/OrganizationResourceTest.java
Related to https://github.com/OpenSRP/opensrp-server-core/issues/325
> Team assignment changes

- src/main/java/org/opensrp/web/rest/StockResource.java
- src/test/java/org/opensrp/web/rest/StockResourceTest.java
> fix issue547

- pom.xml
- src/main/java/org/opensrp/web/GlobalExceptionHandler.java
- src/main/java/org/opensrp/web/controller/UserController.java
- src/main/java/org/opensrp/web/exceptions/MissingTeamAssignmentException.java
- src/main/java/org/opensrp/web/rest/OrganizationResource.java
- src/test/java/org/opensrp/web/rest/OrganizationResourceTest.java
- src/test/java/org/opensrp/web/rest/UserControllerTest.java
- src/test/java/org/opensrp/web/rest/shadow/OrganizationResourceShadow.java
- src/test/java/org/opensrp/web/rest/shadow/UserControllerShadow.java
> User assignment return intersection of assignment jurisdictions with assigned plan's locations

- pom.xml
- src/main/java/org/opensrp/web/rest/PlanResource.java
> Allow fetching of plans for users with more than 1 period in the usernames

- pom.xml
> Upgrade core library to use UTC Timezone

- pom.xml
> Fetch all structures during task generation

- src/main/java/org/opensrp/web/controller/UniqueIdController.java
- src/test/java/org/opensrp/web/controller/UniqueIdControllerTest.java
- src/test/java/org/opensrp/web/utils/UtilsTest.java
- Disbale OpenMRS UID gen feature for v2.2+
> Remove OpenMRS Unique ID fallback

- pom.xml
- src/main/java/org/opensrp/web/Constants.java
- src/main/java/org/opensrp/web/config/Role.java
- src/main/java/org/opensrp/web/controller/UniqueIdController.java
- src/main/java/org/opensrp/web/rest/EventResource.java
- src/main/java/org/opensrp/web/utils/MaskingUtils.java
- src/main/java/org/opensrp/web/utils/Utils.java
- src/test/java/org/opensrp/web/utils/MaskingUtilsTest.java
- src/test/java/org/opensrp/web/utils/UtilsTest.java
- Helper class Masking Utils with masking helper methods
- Support for masking client demographics for the _getAll_ endpoint using role [PII_DATA_MASK](https://github.com/OpenSRP/opensrp-server-web/blob/master/src/main/java/org/opensrp/web/config/Role.java)
> Implement PII data masking

- pom.xml
- src/main/java/org/opensrp/web/dto/TaskDto.java
- src/main/java/org/opensrp/web/dto/TaskSyncRequestWrapper.java
- src/main/java/org/opensrp/web/rest/TaskResource.java
- src/main/java/org/opensrp/web/rest/v2/TaskResource.java
- src/test/java/org/opensrp/web/rest/CampaignResourceTest.java
- src/test/java/org/opensrp/web/rest/TaskResourceTest.java
- src/test/java/org/opensrp/web/rest/v2/TaskResourceV2Test.java
Resolves #616 
Depends on https://github.com/OpenSRP/opensrp-server-core/pull/361
> Task data model changes

- pom.xml
- src/main/java/org/opensrp/web/config/RedisConfig.java
Resolves https://github.com/OpenSRP/opensrp-server-web/issues/479
> 479 : Support Cache for Location hierarchies

- pom.xml
- src/main/java/org/opensrp/web/rest/ClientResource.java
- src/test/java/org/opensrp/web/rest/ClientResourceTest.java
https://github.com/OpenSRP/opensrp-server-web/issues/622
> 622 : search clients by location ids

- pom.xml
> Fix cache eviction when locations are updated

- .github/workflows/docker-publish.yml
Fix Github actions CI to publish Docker image
> Fix Docker Push CI

- pom.xml
- src/main/java/org/opensrp/web/rest/TaskResource.java
- src/test/java/org/opensrp/web/rest/TaskResourceTest.java
Resolves https://github.com/OpenSRP/opensrp-server-web/issues/676
> Mission indicator fix header issue

- pom.xml
> Generate metadata record after main task table has been updated

- pom.xml
- src/main/java/org/opensrp/web/controller/UserController.java
- src/main/java/org/opensrp/web/rest/OrganizationResource.java
- src/test/java/org/opensrp/web/rest/OrganizationResourceTest.java
Resolves #691  and Resolves https://github.com/OpenSRP/opensrp-client-reveal/issues/1218
> user assignment only return active plans

- pom.xml
- src/main/java/org/opensrp/web/rest/StockResource.java
- src/test/java/org/opensrp/web/rest/StockResourceTest.java
Resolves https://github.com/OpenSRP/opensrp-server-web/issues/670
> 670 : Support a draft CSV inventory upload state

- pom.xml
- src/main/java/org/opensrp/web/Constants.java
- src/main/java/org/opensrp/web/rest/ClientFormResource.java
- src/test/java/org/opensrp/web/rest/ClientFormResourceTest.java
> Fix uploading YAML file encoding issue on Windows machines

- pom.xml
Depends on https://github.com/OpenSRP/opensrp-server-core/pull/408 and https://github.com/OpenSRP/opensrp-server-configs/pull/114
> Fix setting of server version

- src/main/java/org/opensrp/web/rest/CustomErrorResource.java
- src/main/webapp/WEB-INF/web.xml
- src/test/java/org/opensrp/web/rest/CustomErrorResourceTest.java
> Add custom error handler

- pom.xml
- src/main/java/org/opensrp/web/rest/UploadController.java
- src/test/java/org/opensrp/web/rest/UploadControllerTest.java
- src/test/java/org/opensrp/web/rest/shadow/UploadControllerShadow.java
Add multi location download feature
> Add multi location download feature

- pom.xml
> Update pom version to 2.4.28

- pom.xml
Related to https://github.com/OpenSRP/opensrp-server-core/pull/415
> Upgrade Jackson core library

- pom.xml
- src/main/java/org/opensrp/web/controller/MultimediaController.java
- src/test/java/org/opensrp/web/controller/MultimediaControllerTest.java
Resolves https://github.com/OpenSRP/opensrp-server-web/issues/731
> 731 : Fix /multimedia/media/{entity-id} to download png images

- pom.xml
- src/main/java/org/opensrp/web/rest/EventResource.java
Resolves https://github.com/OpenSRP/opensrp-server-web/issues/736
> 736 : Resolves Access Denied issue on export event data

- pom.xml
- src/main/java/org/opensrp/web/rest/EventResource.java
Resolves https://github.com/OpenSRP/opensrp-server-web/issues/763
> 763 : Fix missing images in download mission data flow

- pom.xml
- src/main/java/org/opensrp/web/controller/MultimediaController.java
Resolves download S3 images without multimedia directory
> Resolves download S3 images without multimedia directory

- pom.xml
- src/main/java/org/opensrp/web/controller/MultimediaController.java
Checks file manager type to resolve image directory
> Checks file manager type to resolve image directory

- .github/workflows/docker-publish.yml
Use Github Actions to build and publish multiple platform images
Resolves #789
> Add Support for Publishing Multi-platform Image

- pom.xml
- src/main/java/org/opensrp/web/controller/UserController.java
- src/test/java/org/opensrp/web/rest/UserControllerTest.java
> when no default locations are matched from assigned locations, pick from jurisdictions

- pom.xml
- src/main/java/org/opensrp/web/rest/UploadController.java
- src/test/java/org/opensrp/web/rest/UploadControllerTest.java
Falls back to download files from unknown directory
> Falls back to download files from unknown directory

- pom.xml
- src/main/java/org/opensrp/web/rest/SettingResource.java
- src/test/java/org/opensrp/web/rest/SettingResourceTest.java
Related https://github.com/opensrp/opensrp-server-web/issues/820
> 820 : Fix settings adaptation on Settings Resource V1

- pom.xml
> Update server core to v2.11.1-SNAPSHOT

- pom.xml
- src/main/java/org/opensrp/web/Constants.java
- src/main/java/org/opensrp/web/rest/LocationResource.java
- src/test/java/org/opensrp/web/rest/LocationResourceTest.java
Fixes https://github.com/opensrp/opensrp-server-web/issues/831
> Bugfix search location properties by null parentId

- pom.xml
- src/main/resources/spring/applicationContext-opensrp-web.xml
- src/main/webapp/WEB-INF/web.xml
Introduce dhis2-sync-vaccine-tracker profile (for vaccine tracker functionality) to separate from dhis2-sync profile for report events
> add dhis2-sync-vaccine-tracker profile

- pom.xml
- src/main/java/org/opensrp/web/rest/StockResource.java
- src/main/resources/spring/applicationContext-opensrp-web.xml
- src/main/webapp/WEB-INF/web.xml
- src/test/java/org/opensrp/web/rest/StockResourceTest.java
Introduce dhis2-sync-vaccine-tracker profile (for vaccine tracker functionality) to separate from dhis2-sync profile for report events
> update connector remove dhis2 maker on couchdb repo

- src/main/java/org/opensrp/web/utils/SearchHelper.java
- src/test/java/org/opensrp/web/utils/SearchHelperTest.java
> Enable Search by Compass Relationship ID

- pom.xml
- src/main/java/org/opensrp/web/rest/PlanResource.java
- src/test/java/org/opensrp/web/rest/PlanResourceTest.java
> Validate similar case triggered plan does not exist

- pom.xml
> Validate structures during csv upload

- pom.xml
> Upgrade Core Version to 3.0.3

- pom.xml
- src/main/java/org/opensrp/web/rest/TaskResource.java
- src/test/java/org/opensrp/web/rest/TaskResourceTest.java
> Add task status update debug logs

- pom.xml
- src/main/java/org/opensrp/web/rest/EventResource.java
- src/test/java/org/opensrp/web/rest/EventResourceTest.java
closes #929
linked to https://github.com/opensrp/opensrp-server-core/pull/498
> update server-core, for events check for case number and flag

- pom.xml
- src/main/java/org/opensrp/web/rest/ClientFormResource.java
> Specify utf-8 charset in the content type header when fetching client forms

- pom.xml
- src/main/java/org/opensrp/web/controller/MultimediaController.java
> 951 csv download failure on windows

- pom.xml
- src/main/java/org/opensrp/web/rest/UploadController.java
- src/test/java/org/opensrp/web/rest/UploadControllerTest.java
> Resolve event locationid from school

- pom.xml
- src/main/java/org/opensrp/web/rest/OrganizationResource.java
- src/test/java/org/opensrp/web/rest/OrganizationResourceTest.java
https://github.com/opensrp/opensrp-server-web/issues/936
> Create an endpoint that allows querying of team assignment using practitioner's identifier

- src/main/java/org/opensrp/web/rest/TemplateResource.java
> add GET/PUT/POST endpoints for Template

- pom.xml
- src/main/java/org/opensrp/web/rest/EventResource.java
- src/test/java/org/opensrp/web/rest/EventResourceTest.java
> Remove duplicate case details event check

- README.md
- pom.xml
- src/main/java/org/opensrp/web/Constants.java
- src/main/java/org/opensrp/web/config/security/SecurityConfig.java
- src/main/java/org/opensrp/web/contract/ServiceHealthIndicator.java
- src/main/java/org/opensrp/web/controller/HealthController.java
- src/main/java/org/opensrp/web/health/JdbcServiceHealthIndicator.java
- src/main/java/org/opensrp/web/health/KeycloakServiceHealthIndicator.java
- src/main/java/org/opensrp/web/health/RabbitmqServiceHealthIndicator.java
- src/main/java/org/opensrp/web/health/RedisServiceHealthIndicator.java
- src/main/java/org/opensrp/web/health/ServiceHealthIndicator.java
- src/main/java/org/opensrp/web/service/HealthService.java
- src/main/java/org/opensrp/web/serviceimpl/HealthServiceImpl.java
- src/test/java/org/opensrp/TestDatabaseConfig.java
- src/test/java/org/opensrp/web/controller/HealthControllerTest.java
- src/test/java/org/opensrp/web/health/JdbcServiceHealthIndicatorTest.java
- src/test/java/org/opensrp/web/health/KeycloakServiceHealthIndicatorTest.java
- src/test/java/org/opensrp/web/health/RabbitmqServiceHealthIndicatorTest.java
- src/test/java/org/opensrp/web/health/RedisServiceHealthIndicatorTest.java
- src/test/java/org/opensrp/web/rest/OrganizationResourceTest.java
- src/test/java/org/opensrp/web/serviceimpl/HealthServiceImplTest.java
- src/test/resources/test-webmvc-config.xml
Sample output
```json
{
"problems": {
},
"services": {
"postgres": true,
"redis": true,
"keycloak": true
},
"serverTime": "2021-11-03T15:45:53.942+03:00",
"version": "2.8.29-SNAPSHOT",
"gitBuildTime": "2021-11-03T15:44:42+0300",
"gitCommitId": "be29446c3dfc12147b9d4e289439cdb4fd940f97"
}
```
> add health endpoint

- README.md
- pom.xml
- src/main/java/org/opensrp/web/Constants.java
- src/main/java/org/opensrp/web/serviceimpl/HealthServiceImpl.java
- src/test/java/org/opensrp/web/health/RabbitmqServiceHealthIndicatorTest.java
- src/test/java/org/opensrp/web/health/RedisServiceHealthIndicatorTest.java
- src/test/java/org/opensrp/web/serviceimpl/HealthServiceImplTest.java
- src/test/resources/test-webmvc-config.xml
Removing gitcommitid plugin since maven-war plugin can generate the manifest properties needed. GitcommitId plugin added in this [PR](https://github.com/opensrp/opensrp-server-web/pull/981).
> Update build version source

- README.md
- pom.xml
- src/main/java/org/opensrp/web/Constants.java
- src/main/java/org/opensrp/web/serviceimpl/HealthServiceImpl.java
- src/test/java/org/opensrp/web/health/RabbitmqServiceHealthIndicatorTest.java
- src/test/java/org/opensrp/web/health/RedisServiceHealthIndicatorTest.java
- src/test/java/org/opensrp/web/serviceimpl/HealthServiceImplTest.java
- src/test/resources/test-webmvc-config.xml
Removing gitcommitid plugin since maven-war plugin can generate the manifest properties needed. GitcommitId plugin added in this [PR](https://github.com/opensrp/opensrp-server-web/pull/983).
> Update build version source v3

- pom.xml
- src/main/java/org/opensrp/web/health/RedisServiceHealthIndicator.java
- src/test/java/org/opensrp/web/health/RedisServiceHealthIndicatorTest.java
So apparently redis does not close connection after a request, added a fix to close the connection after the health check.
> Redis close connection indicator v2.1

- pom.xml
- src/main/java/org/opensrp/web/health/RedisServiceHealthIndicator.java
- src/test/java/org/opensrp/web/health/RedisServiceHealthIndicatorTest.java
So apparently redis does not close connection after a request, added a fix to close the connection after the health check.
> Redis close connection indicator

- pom.xml
- src/main/java/org/opensrp/web/health/RedisServiceHealthIndicator.java
- src/test/java/org/opensrp/web/health/RedisServiceHealthIndicatorTest.java
So apparently redis does not close connection after a request, added a fix to close the connection after the health check.
> Redis close connection indicator v3

- pom.xml
> Update assigned location and plans fetch size

- pom.xml
- src/main/java/org/opensrp/web/rest/PlanResource.java
- src/test/java/org/opensrp/web/rest/PlanResourceTest.java
> API End point to return count of plans with missed task generation and their details

- pom.xml
- src/main/java/org/opensrp/web/rest/EventResource.java
- Fix error level issue (error logs in-place of info logs) on event add endpoint.
- Update sentry and log4j dependencies.
> fix error level issue on event add endpoint

- pom.xml
Resolves issue logged [here](https://github.com/opensrp/opensrp-server-web/issues/1046)
> Fix missing plan task count bug

- pom.xml
- Update [server configs](https://github.com/OpenSRP/opensrp-server-configs/tree/master).
> update server configs and snapshot version

- pom.xml
- src/main/java/org/opensrp/web/Constants.java
- src/main/java/org/opensrp/web/rest/OrganizationResource.java
- src/main/java/org/opensrp/web/rest/PractitionerResource.java
- src/test/java/org/opensrp/web/rest/OrganizationResourceTest.java
- src/test/java/org/opensrp/web/rest/PractitionerResourceTest.java
See https://github.com/opensrp/opensrp-server-core/issues/521 for details
> Add server version, date created and date edited to Practitioner and Organization Resources

- pom.xml
> Fix plan generation for index cases with local case classification

- pom.xml
- src/main/java/org/opensrp/web/config/security/BasicAuthSecurityConfig.java
- src/main/java/org/opensrp/web/config/security/OAuth2SecurityConfig.java
- src/main/java/org/opensrp/web/controller/ActionController.java
> Allow /actions Fetch via POST for v2.1

- Dockerfile
- pom.xml
- closes #1088 
- use tomcat correto jdk images.
> Add mybatis runtime feature v2.2

- pom.xml
> Update pom.xml to version 2.11.0

- pom.xml
Reverts opensrp/opensrp-server-web#1107
> Revert "Update pom.xml to version 2.11.0"

- pom.xml
- src/main/java/org/opensrp/web/rest/EventResource.java
- src/test/java/org/opensrp/web/rest/BaseSecureResourceTest.java
- src/test/java/org/opensrp/web/rest/EventResourceTest.java
> Log and Return Failed Sync Events & Clients

- pom.xml
- src/main/java/org/opensrp/web/rest/EventResource.java
> Log and Return Failed Sync Events & Clients for v2.1

- pom.xml
- src/main/java/org/opensrp/web/acl/ClientPermissionEvaluator.java
- src/main/java/org/opensrp/web/acl/EventPermissionEvaluator.java
- src/main/java/org/opensrp/web/acl/LocationPermissionEvaluator.java
- src/main/java/org/opensrp/web/acl/OrganizationPermissionEvaluator.java
- src/main/java/org/opensrp/web/acl/PlanPermissionEvaluator.java
- src/main/java/org/opensrp/web/acl/UserPermissionEvaluator.java
- src/main/java/org/opensrp/web/rest/ValidateResource.java
> ACL Resolve Missing Object Permission

- pom.xml
- src/main/java/org/opensrp/web/rest/EventResource.java
Include request JSON for each failed clients and events in the log entry for troubleshooting
> Log More Details for Clients/Events That Fail to Sync for v2.1

- pom.xml
- src/main/java/org/opensrp/web/rest/EventResource.java
Include request JSON for each failed clients and events in the log entry for troubleshooting
> Log More Details for Clients/Events That Fail to Sync for v2.2

- README.md
- pom.xml
- src/main/java/org/opensrp/web/config/RedisConfig.java
- src/test/java/org/opensrp/web/config/RedisConfigTest.java
- closes #1140 
- Add support for no password redis configuration.
> add redis sentinel configuration v2.2

- README.md
- pom.xml
- src/main/java/org/opensrp/web/config/RedisConfig.java
- src/test/java/org/opensrp/web/config/RedisConfigTest.java
- #1140 
- Add support for no password redis configuration.
> Add redis sentinel feature master

- pom.xml
Related issue https://github.com/opensrp/opensrp-server-web/issues/1151
> update to opensrp-server-core with jackson-databind security update

- pom.xml
Part of the fixes for https://github.com/opensrp/opensrp-server-web/issues/1151
> [v.2.2] Upgrade snakeyaml version to 1.33
